name: "godot-ci export"
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.1.2
  EXPORT_NAME: endlessVoyage

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: export game
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.2/Godot_v4.1.2-stable_linux.x86_64.zip 
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.2/Godot_v4.1.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Copy dirty Githubpages-Hack File to webs dir
        run: cp /home/runner/work/endlessVoyage/endlessVoyage/coi-serviceworker.js /home/runner/.local/share/godot/builds/web

      - name: Activate dirty Githubpages-File
        run: sed -i -e 's/<head>/<head><script src="coi-serviceworker.js"><\/script>/g' /home/runner/.local/share/godot/builds/web/index.html

            #      - name: Copy Windows zip to web deploy dir
            #        run: cp /home/runner/.local/share/godot/archives/win.zip /home/runner/.local/share/godot/builds/web

            #      - name: Copy Linux zip to web deploy dir
            #        run: cp /home/runner/.local/share/godot/archives/linux.zip /home/runner/.local/share/godot/builds/web

            #      - name: Copy Android zip to web deploy dir
            #        run: cp /home/runner/.local/share/godot/archives/android.zip /home/runner/.local/share/godot/builds/web

          #      - name: Deploy to GitHub Pages        
          #        uses: JamesIves/github-pages-deploy-action@releases/v4
          #        with:
          #          folder: /home/runner/.local/share/godot/builds/web                  

      - name: Deploy to itch.io
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: /home/runner/.local/share/godot/builds/web
          itchUsername: endlessvoyage
          itchGameId: endlessvoyage
          buildChannel: web
            
